spring:
  application:
    name: healthcare-api-service
  datasource:
    url: jdbc:postgresql://localhost:5433/healthcare
    username: postgres
    password: Admin@123
    driver-class-name: org.postgresql.Driver